site_name: GXJ's Notes
# site_url: https://example.com/

nav:
  - Home: index.md
  - Go: 
    - 基础语法: Go/基础语法/index.md
    - 第三方库:
      - Gorm: 
        - 通用CURD方法: Go/第三方库/Gorm/通用CURD方法.md
  - MkDocs:
    - 安装及部署: MkDocs/index.md
theme: readthedocs
